# Generated by Django 5.2.7 on 2025-10-24 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_tracker', '0002_alter_balance_amount_alter_balance_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balance',
            options={'managed': True, 'verbose_name': 'Balance', 'verbose_name_plural': 'Balances'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'managed': True, 'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'managed': True, 'verbose_name': 'UserProfile', 'verbose_name_plural': 'UserProfiles'},
        ),
        migrations.AlterModelTable(
            name='balance',
            table='balance',
        ),
        migrations.AlterModelTable(
            name='transaction',
            table='transaction',
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='user_profile',
        ),
    ]
