# Generated by Django 5.2.7 on 2025-11-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_tracker', '0003_alter_balance_options_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='Profile Image'),
        ),
    ]
