# Generated by Django 5.2.7 on 2025-11-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_tracker', '0004_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default=1, upload_to='profiles/'),
            preserve_default=False,
        ),
    ]
